name: Update hu_urom feed

on:
  push:
    branches: main

defaults:
  run:
    working-directory: hu_urom

jobs:

  upload-zip:
    name: Package and upload to AWS S3
    
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package GTFS
        run: zip gtfs_hu_urom.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to AWS S3
        run: |
          aws s3 cp gtfs_hu_urom.zip s3://gtfs-gy-mate/ \
            --content-disposition attachment
